### ISSUE TITLE
Lowercase-ify capital letters in command line arguments and use argparse rather than sys args

### ISSUE THREAD

**Issue by mccbc** [vanlellan/nameTartan#1]
Request support for capital letters! `name.lower()` would work. If there are any more features to add to the command line args, [argparse](https://stackoverflow.com/a/35365469) would be an improvement on `sys.argv`.

Sidenote, this is a really cool project.

Terminal output:
```
$ python nameTartanHSV.py Brian Connor McClellan
Last Name: McClellan [-20, 2, -30, 11, 4, 11, 11, 0, 13]
Middle Name: Connor [-30, 14, 13, 13, 14, 17]
First Name: Brian [-31, 17, 8, 0, 13]
Traceback (most recent call last):
  File "nameTartanHSV.py", line 73, in <module>
    w.write(outFile, img)
  File "/home/connor/anaconda3/lib/python3.7/site-packages/png.py", line 668, in write
    nrows = self.write_passes(outfile, check_rows(rows))
  File "/home/connor/anaconda3/lib/python3.7/site-packages/png.py", line 703, in write_passes
    return self.write_packed(outfile, rows)
  File "/home/connor/anaconda3/lib/python3.7/site-packages/png.py", line 747, in write_packed
    data.extend(row)
ValueError: byte must be in range(0, 256)
```

**Comment by vanlellan** [comment]
Thanks! string.lower() implemented!
